### ISSUE TITLE
Project has a class not found error

### ISSUE THREAD

**Issue by dragon74** [camunda/camunda-get-started-spring-boot#3]
I downloaded it, maven installed successfully and ran it. Got a class not found exception for some class that is in your webapp and is not added to the project classpath:

**Caused by: java.lang.NoClassDefFoundError: org/camunda/bpm/welcome/impl/web/bootstrap/WelcomeContainerBootstrap**
	at org.camunda.bpm.spring.boot.starter.webapp.CamundaBpmWebappInitializer.onStartup(CamundaBpmWebappInitializer.java:58) ~[camunda-bpm-spring-boot-starter-webapp-core-3.0.0.jar:3.0.0]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.selfInitialize(ServletWebServerApplicationContext.java:238) ~[spring-boot-2.0.2.RELEASE.jar:2.0.2.RELEASE]
	at org.springframework.boot.web.embedded.tomcat.TomcatStarter.onStartup(TomcatStarter.java:54) ~[spring-boot-2.0.2.RELEASE.jar:2.0.2.RELEASE]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5245) ~[tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-8.5.31.jar:8.5.31]
	... 6 common frames omitted

**Comment by yanavasileva** [comment]
Hi @dragon74,

Is the issue still persist?

Best regards,
Yana

**Comment by dragon74** [comment]
no

**Comment by yanavasileva** [comment]
In this case hereby I am closing the issue.
